# Generated by Django 5.1.15 on 2026-05-09 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busquedas', '0009_searchprofile_min_area_m2_searchprofile_min_price'),
        ('inmuebles', '0005_capturedproperty_possible_duplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email')),
                ('provider_label', models.CharField(blank=True, max_length=80, verbose_name='proveedor')),
                ('imap_host', models.CharField(blank=True, max_length=180, verbose_name='host IMAP')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='puerto IMAP')),
                ('imap_use_ssl', models.BooleanField(default=True, verbose_name='usar SSL')),
                ('imap_username', models.CharField(blank=True, max_length=180, verbose_name='usuario IMAP')),
                ('imap_password', models.CharField(blank=True, max_length=255, verbose_name='contraseña IMAP')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='última sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'Cuenta de email',
                'verbose_name_plural': 'Cuentas de email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('reviewed', 'Revisado'), ('converted', 'Convertido en captación'), ('discarded', 'Descartado')], default='new', max_length=20, verbose_name='estado')),
                ('message_uid', models.CharField(blank=True, max_length=180, verbose_name='UID mensaje')),
                ('message_id', models.CharField(blank=True, max_length=255, verbose_name='Message-ID')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='asunto')),
                ('from_name', models.CharField(blank=True, max_length=180, verbose_name='nombre remitente')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='email remitente')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='recibido')),
                ('snippet', models.TextField(blank=True, verbose_name='resumen')),
                ('body_text', models.TextField(blank=True, verbose_name='cuerpo texto')),
                ('detected_urls', models.JSONField(blank=True, default=list, verbose_name='URLs detectadas')),
                ('raw_metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='inbox.emailaccount', verbose_name='cuenta')),
                ('captured_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='inmuebles.capturedproperty', verbose_name='captación creada')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
                ('search_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='busquedas.searchprofile', verbose_name='expediente/búsqueda')),
            ],
            options={
                'verbose_name': 'Email entrante',
                'verbose_name_plural': 'Emails entrantes',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['owner', 'is_active'], name='inbox_email_owner_i_393acc_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['email_address'], name='inbox_email_email_a_e0e4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['owner', 'status'], name='inbox_inbou_owner_i_0abb07_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['account', 'message_uid'], name='inbox_inbou_account_638807_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['received_at'], name='inbox_inbou_receive_0e7809_idx'),
        ),
    ]
