# Generated by Django 5.1.15 on 2026-04-18 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmuebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('website', models.URLField(blank=True, verbose_name='web')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'Comercializadora',
                'verbose_name_plural': 'Comercializadoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('agent', 'Agente'), ('broker', 'Intermediario'), ('assistant', 'Asistente'), ('other', 'Otro')], default='other', max_length=20, verbose_name='rol')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('preferred_channel', models.CharField(choices=[('phone', 'Teléfono'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('unknown', 'Desconocido')], default='unknown', max_length=20, verbose_name='canal preferido')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'Contacto de oportunidad',
                'verbose_name_plural': 'Contactos de oportunidad',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('active', 'Activa'), ('analysis', 'Análisis'), ('negotiation', 'Negociación'), ('discarded', 'Descartada'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='prioridad')),
                ('asking_price_current', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio actual')),
                ('target_price_internal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio objetivo interno')),
                ('next_action', models.CharField(blank=True, max_length=255, verbose_name='siguiente acción')),
                ('next_review_at', models.DateTimeField(blank=True, null=True, verbose_name='próxima revisión')),
                ('opportunity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score oportunidad')),
                ('decision_notes', models.TextField(blank=True, verbose_name='notas de decisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='asignado a')),
                ('broker_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='seguimiento.brokercompany', verbose_name='comercializadora')),
                ('captured_property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity', to='inmuebles.capturedproperty', verbose_name='inmueble captado')),
                ('main_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='seguimiento.opportunitycontact', verbose_name='contacto principal')),
            ],
            options={
                'verbose_name': 'Oportunidad inmobiliaria',
                'verbose_name_plural': 'Oportunidades inmobiliarias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='seguimiento_status_7dbafd_idx'), models.Index(fields=['priority'], name='seguimiento_priorit_bf60b7_idx'), models.Index(fields=['next_review_at'], name='seguimiento_next_re_88fd52_idx')],
            },
        ),
    ]
