# Generated by Django 5.1.15 on 2026-04-18 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('new_capture', 'Nueva captación'), ('price_drop', 'Bajada de precio'), ('review_overdue', 'Revisión vencida'), ('possible_duplicate', 'Posible duplicado'), ('listing_unavailable', 'Anuncio no disponible'), ('opportunity_inactive', 'Oportunidad inactiva'), ('info', 'Información')], default='info', max_length=40, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='severidad')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('seen', 'Vista'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='new', max_length=15, verbose_name='estado')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('captured_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inmuebles.capturedproperty', verbose_name='inmueble captado')),
                ('property_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='seguimiento.propertyopportunity', verbose_name='oportunidad')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type'], name='seguimiento_alert_t_dc3fbd_idx'), models.Index(fields=['severity'], name='seguimiento_severit_2e280a_idx'), models.Index(fields=['status'], name='seguimiento_status_2bddb7_idx'), models.Index(fields=['created_at'], name='seguimiento_created_aa3477_idx')],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('review', 'Revisión'), ('price_check', 'Revisión de precio'), ('contact_owner', 'Contactar'), ('validate_data', 'Validar datos'), ('follow_up', 'Seguimiento')], default='follow_up', max_length=30, verbose_name='tipo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En progreso'), ('done', 'Hecha'), ('cancelled', 'Cancelada')], default='open', max_length=20, verbose_name='estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='prioridad')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha límite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to=settings.AUTH_USER_MODEL, verbose_name='asignado a')),
                ('captured_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inmuebles.capturedproperty', verbose_name='inmueble captado')),
                ('property_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='seguimiento.propertyopportunity', verbose_name='oportunidad')),
            ],
            options={
                'verbose_name': 'Tarea de seguimiento',
                'verbose_name_plural': 'Tareas de seguimiento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_type'], name='seguimiento_task_ty_ff2c33_idx'), models.Index(fields=['status'], name='seguimiento_status_042741_idx'), models.Index(fields=['priority'], name='seguimiento_priorit_091587_idx'), models.Index(fields=['due_date'], name='seguimiento_due_dat_c479c5_idx')],
            },
        ),
    ]
