# Generated by Django 5.1.15 on 2026-04-22 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_capturedproperty_operation_type_and_more'),
        ('seguimiento', '0002_alert_followuptask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Creación'), ('note', 'Nota'), ('call', 'Llamada'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('visit', 'Visita'), ('document_request', 'Solicitud de documento'), ('document_received', 'Documento recibido'), ('status_change', 'Cambio de estado'), ('price_update', 'Actualización de precio'), ('task', 'Tarea')], default='note', max_length=30, verbose_name='tipo de actividad')),
                ('summary', models.CharField(max_length=220, verbose_name='resumen')),
                ('details', models.TextField(blank=True, verbose_name='detalle')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='datos extra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'Actividad de oportunidad',
                'verbose_name_plural': 'Actividades de oportunidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='propertyopportunity',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Oportunidad inmobiliaria', 'verbose_name_plural': 'Oportunidades inmobiliarias'},
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='address_text',
            field=models.CharField(blank=True, max_length=220, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='cadastral_reference',
            field=models.CharField(blank=True, max_length=40, verbose_name='referencia catastral'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='discard_reason',
            field=models.TextField(blank=True, verbose_name='motivo de descarte'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='estimated_gross_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='rentabilidad bruta estimada (%)'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='expected_rent_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='renta mensual esperada'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última actividad'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='max_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='oferta máxima'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='municipality',
            field=models.CharField(blank=True, max_length=120, verbose_name='municipio'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='código postal'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='simple_note_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha nota simple'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='simple_note_status',
            field=models.CharField(choices=[('unknown', 'Sin revisar'), ('pending', 'Pendiente'), ('requested', 'Solicitada'), ('received', 'Recibida'), ('reviewed', 'Revisada')], default='unknown', max_length=20, verbose_name='estado nota simple'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='summary',
            field=models.TextField(blank=True, verbose_name='resumen ejecutivo'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='zone',
            field=models.CharField(blank=True, max_length=150, verbose_name='zona'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='status',
            field=models.CharField(choices=[('new', 'Nueva'), ('active', 'Activa'), ('analysis', 'Análisis'), ('documentation', 'Documentación'), ('visit_pending', 'Visita pendiente'), ('negotiation', 'Negociación'), ('discarded', 'Descartada'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='estado'),
        ),
        migrations.AddIndex(
            model_name='propertyopportunity',
            index=models.Index(fields=['province'], name='seguimiento_provinc_c361ba_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyopportunity',
            index=models.Index(fields=['municipality'], name='seguimiento_municip_b05bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyopportunity',
            index=models.Index(fields=['zone'], name='seguimiento_zone_d9a5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyopportunity',
            index=models.Index(fields=['last_activity_at'], name='seguimiento_last_ac_7e5e4a_idx'),
        ),
        migrations.AddField(
            model_name='opportunityactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_activities', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='opportunityactivity',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='seguimiento.propertyopportunity', verbose_name='oportunidad'),
        ),
        migrations.AddIndex(
            model_name='opportunityactivity',
            index=models.Index(fields=['activity_type'], name='seguimiento_activit_1ecd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityactivity',
            index=models.Index(fields=['created_at'], name='seguimiento_created_66c975_idx'),
        ),
    ]
