# Generated by Django 5.1.15 on 2026-04-25 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_capturedproperty_operation_type_and_more'),
        ('seguimiento', '0003_opportunityactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propertyopportunity',
            name='seguimiento_zone_d9a5d0_idx',
        ),
        migrations.RemoveField(
            model_name='propertyopportunity',
            name='next_action',
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='next_action_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='detalle de siguiente acción'),
        ),
        migrations.AddField(
            model_name='propertyopportunity',
            name='next_action_type',
            field=models.CharField(choices=[('call', 'Llamar'), ('request_docs', 'Pedir documentación'), ('schedule_visit', 'Agendar visita'), ('validate_data', 'Validar datos'), ('review_profitability', 'Revisar rentabilidad'), ('make_offer', 'Hacer oferta'), ('negotiate', 'Negociar'), ('discard', 'Descartar'), ('other', 'Otra')], default='other', max_length=30, verbose_name='tipo de siguiente acción'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='address_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='dirección o referencia'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='cadastral_reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='referencia catastral'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, verbose_name='municipio'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='opportunity_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='score oportunidad'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='simple_note_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('requested', 'Solicitada'), ('received', 'Recibida'), ('reviewed', 'Revisada'), ('not_applicable', 'No aplica')], default='pending', max_length=20, verbose_name='estado nota simple'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='status',
            field=models.CharField(choices=[('new', 'Nueva'), ('active', 'Activa'), ('analysis', 'En análisis'), ('negotiation', 'En negociación'), ('discarded', 'Descartada'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='propertyopportunity',
            name='summary',
            field=models.TextField(blank=True, verbose_name='resumen operativo'),
        ),
        migrations.AddIndex(
            model_name='propertyopportunity',
            index=models.Index(fields=['next_action_type'], name='seguimiento_next_ac_593461_idx'),
        ),
    ]
