# Generated by Django 5.1.15 on 2026-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_remove_propertyopportunity_seguimiento_zone_d9a5d0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyopportunity',
            name='next_action_type',
            field=models.CharField(choices=[('call', 'Llamar'), ('wait_response', 'Esperar respuesta'), ('request_docs', 'Pedir documentación'), ('schedule_visit', 'Agendar visita'), ('validate_data', 'Validar datos'), ('review_profitability', 'Revisar rentabilidad'), ('make_offer', 'Hacer oferta'), ('negotiate', 'Negociar'), ('discard', 'Descartar'), ('other', 'Otra')], default='other', max_length=30, verbose_name='tipo de siguiente acción'),
        ),
    ]
