# Generated by Django 5.1.15 on 2026-04-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_alter_propertyopportunity_next_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
    ]
