# Generated by Django 5.1.15 on 2026-04-26 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0009_alter_propertyopportunity_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuptask',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_followup_tasks', to=settings.AUTH_USER_MODEL, verbose_name='propietario'),
        ),
    ]
