# Generated by Django 5.1.15 on 2026-04-27 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0007_searchprofile_automation_enabled_and_more'),
        ('inmuebles', '0005_capturedproperty_possible_duplicate'),
        ('seguimiento', '0014_alter_opportunitycontact_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyopportunity',
            name='search_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='busquedas.searchprofile', verbose_name='búsqueda'),
        ),
        migrations.AddIndex(
            model_name='propertyopportunity',
            index=models.Index(fields=['search_profile'], name='seguimiento_search__1002f0_idx'),
        ),
    ]
