# Generated by Django 5.1.15 on 2026-04-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('province', models.CharField(max_length=100, verbose_name='provincia')),
                ('property_types', models.JSONField(blank=True, default=list, verbose_name='tipos de propiedad')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio máximo')),
                ('min_bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='dormitorios mínimos')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'Perfil de búsqueda',
                'verbose_name_plural': 'Perfiles de búsqueda',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['province'], name='busquedas_s_provinc_fb01fb_idx'), models.Index(fields=['is_active'], name='busquedas_s_is_acti_81aa6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completada'), ('completed_with_errors', 'Completada con errores'), ('failed', 'Fallida')], default='pending', max_length=30, verbose_name='estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('total_found', models.PositiveIntegerField(default=0, verbose_name='total encontrados')),
                ('total_new', models.PositiveIntegerField(default=0, verbose_name='total nuevos')),
                ('total_updated', models.PositiveIntegerField(default=0, verbose_name='total actualizados')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='total errores')),
                ('run_notes', models.TextField(blank=True, verbose_name='notas de ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('search_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='busquedas.searchprofile', verbose_name='perfil de búsqueda')),
            ],
            options={
                'verbose_name': 'Ejecución de búsqueda',
                'verbose_name_plural': 'Ejecuciones de búsqueda',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='busquedas_s_status_aac79f_idx'), models.Index(fields=['created_at'], name='busquedas_s_created_9fe6a7_idx')],
            },
        ),
    ]
