# Generated by Django 5.1.15 on 2026-04-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='error'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='execution_mode',
            field=models.CharField(choices=[('mock', 'Mock'), ('ai_discovery', 'Exploración IA'), ('portal', 'Portal'), ('email', 'Email')], default='mock', max_length=30, verbose_name='modo de ejecución'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='filters_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='snapshot de filtros'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='query_text',
            field=models.TextField(blank=True, verbose_name='consulta generada'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='respuesta cruda'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='total_candidates',
            field=models.PositiveIntegerField(default=0, verbose_name='candidatos totales'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='total_valid_candidates',
            field=models.PositiveIntegerField(default=0, verbose_name='candidatos válidos'),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='warnings',
            field=models.JSONField(blank=True, default=list, verbose_name='warnings'),
        ),
        migrations.AddIndex(
            model_name='searchrun',
            index=models.Index(fields=['execution_mode'], name='busquedas_s_executi_8c59a2_idx'),
        ),
    ]
