# Generated by Django 5.1.15 on 2026-04-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0002_searchrun_error_message_searchrun_execution_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='ai_prompt',
            field=models.TextField(blank=True, verbose_name='texto guía para IA'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='operation_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler')], default='sale', max_length=20, verbose_name='tipo de operación'),
        ),
        migrations.AddIndex(
            model_name='searchprofile',
            index=models.Index(fields=['operation_type'], name='busquedas_s_operati_735db1_idx'),
        ),
    ]
