# Generated by Django 5.1.15 on 2026-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0003_searchprofile_ai_prompt_searchprofile_operation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='zone',
            field=models.CharField(blank=True, max_length=150, verbose_name='zona / municipio'),
        ),
        migrations.AddIndex(
            model_name='searchprofile',
            index=models.Index(fields=['zone'], name='busquedas_s_zone_9da5d0_idx'),
        ),
    ]
