# Generated by Django 5.1.15 on 2026-04-27 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0006_alter_searchprofile_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Si está desactivado, esta búsqueda no se ejecutará automáticamente.', verbose_name='automatización IA activada'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'Azul'), ('green', 'Verde'), ('orange', 'Naranja'), ('purple', 'Morado'), ('red', 'Rojo'), ('teal', 'Turquesa')], max_length=20, verbose_name='color operativo'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='outcome_notes',
            field=models.TextField(blank=True, verbose_name='notas de desenlace'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('closed_with_opportunity', 'Cerrada con oportunidad'), ('closed_empty', 'Cerrada desierta'), ('archived', 'Archivada')], default='active', max_length=40, verbose_name='estado'),
        ),
        migrations.AddIndex(
            model_name='searchprofile',
            index=models.Index(fields=['status'], name='busquedas_s_status_8d2351_idx'),
        ),
        migrations.AddIndex(
            model_name='searchprofile',
            index=models.Index(fields=['color'], name='busquedas_s_color_69065d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchprofile',
            index=models.Index(fields=['owner', 'status'], name='busquedas_s_owner_i_02795c_idx'),
        ),
    ]
