# Generated by Django 5.1.15 on 2026-04-27 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0007_searchprofile_automation_enabled_and_more'),
        ('seguimiento', '0015_propertyopportunity_search_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='selected_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_searches', to='seguimiento.propertyopportunity', verbose_name='oportunidad seleccionada'),
        ),
    ]
