# Generated by Django 5.1.15 on 2026-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0008_searchprofile_selected_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofile',
            name='min_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='metros mínimos'),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio mínimo'),
        ),
    ]
