# Generated by Django 5.1.15 on 2026-04-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busquedas', '0001_initial'),
        ('fuentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_mode', models.CharField(choices=[('structured_capture', 'Captación estructurada'), ('ai_exploration', 'Exploración IA'), ('manual', 'Manual')], default='structured_capture', max_length=30, verbose_name='modo de entrada')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='url origen')),
                ('source_external_id', models.CharField(blank=True, max_length=255, verbose_name='id externo')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description_raw', models.TextField(blank=True, verbose_name='descripción original')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('municipality', models.CharField(blank=True, max_length=120, verbose_name='municipio')),
                ('zone_text', models.CharField(blank=True, max_length=255, verbose_name='zona')),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('land', 'Terreno'), ('flat', 'Piso')], max_length=20, verbose_name='tipo de propiedad')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='dormitorios')),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='baños')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='superficie m2')),
                ('status', models.CharField(choices=[('captured', 'Captado'), ('in_review', 'En revisión'), ('validated', 'Validado'), ('discarded', 'Descartado')], default='captured', max_length=20, verbose_name='estado')),
                ('review_status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('reviewed_with_changes', 'Revisado con cambios')], default='pending', max_length=30, verbose_name='estado de revisión')),
                ('is_interesting', models.BooleanField(default=False, verbose_name='interesante')),
                ('ai_summary', models.TextField(blank=True, verbose_name='resumen IA')),
                ('ai_signals', models.JSONField(blank=True, default=list, verbose_name='señales IA')),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score IA')),
                ('manual_notes', models.TextField(blank=True, verbose_name='notas manuales')),
                ('discard_reason', models.CharField(blank=True, max_length=100, verbose_name='motivo de descarte')),
                ('published_at_source', models.DateTimeField(blank=True, null=True, verbose_name='publicado en origen')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='captado en')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='última vez visto')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='última revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('search_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_properties', to='busquedas.searchprofile', verbose_name='perfil de búsqueda')),
                ('search_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_properties', to='busquedas.searchrun', verbose_name='ejecución de búsqueda')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_properties', to='fuentes.source', verbose_name='fuente')),
            ],
            options={
                'verbose_name': 'Inmueble captado',
                'verbose_name_plural': 'Inmuebles captados',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['status'], name='inmuebles_c_status_ef39b6_idx'), models.Index(fields=['review_status'], name='inmuebles_c_review__f04928_idx'), models.Index(fields=['is_interesting'], name='inmuebles_c_is_inte_fc5689_idx'), models.Index(fields=['property_type'], name='inmuebles_c_propert_8269cb_idx'), models.Index(fields=['province'], name='inmuebles_c_provinc_fc43ae_idx'), models.Index(fields=['municipality'], name='inmuebles_c_municip_741dfe_idx'), models.Index(fields=['price'], name='inmuebles_c_price_32a6cb_idx'), models.Index(fields=['captured_at'], name='inmuebles_c_capture_4bcd35_idx'), models.Index(fields=['source_external_id'], name='inmuebles_c_source__c7c539_idx')],
            },
        ),
    ]
