# Generated by Django 5.1.15 on 2026-04-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0003_searchprofile_ai_prompt_searchprofile_operation_type_and_more'),
        ('fuentes', '0001_initial'),
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedproperty',
            name='operation_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler')], default='sale', max_length=20, verbose_name='tipo de operación'),
        ),
        migrations.AlterField(
            model_name='capturedproperty',
            name='property_type',
            field=models.CharField(choices=[('house', 'Casa'), ('land', 'Terreno'), ('flat', 'Piso'), ('commercial', 'Local')], max_length=20, verbose_name='tipo de propiedad'),
        ),
        migrations.AddIndex(
            model_name='capturedproperty',
            index=models.Index(fields=['operation_type'], name='inmuebles_c_operati_385853_idx'),
        ),
    ]
