# Generated by Django 5.1.15 on 2026-04-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_capturedproperty_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedproperty',
            name='possible_duplicate',
            field=models.BooleanField(default=False, verbose_name='posible duplicado'),
        ),
    ]
