# Generated by Django 5.1.15 on 2026-05-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_capturedproperty_possible_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedproperty',
            name='entry_mode',
            field=models.CharField(choices=[('structured_capture', 'Captación estructurada'), ('ai_exploration', 'Exploración IA'), ('manual', 'Manual'), ('email', 'Email')], default='structured_capture', max_length=30, verbose_name='modo de entrada'),
        ),
    ]
