# Generated by Django 5.1.15 on 2026-08-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inmuebles", "0006_alter_capturedproperty_entry_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="capturedproperty",
            name="availability_verification_note",
            field=models.TextField(blank=True, verbose_name="nota de verificación"),
        ),
        migrations.AddField(
            model_name="capturedproperty",
            name="availability_verification_state",
            field=models.CharField(
                choices=[
                    ("unknown", "Sin verificar"),
                    ("confirmed", "Disponible"),
                    ("unavailable", "No disponible"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
                verbose_name="disponibilidad",
            ),
        ),
        migrations.AddField(
            model_name="capturedproperty",
            name="availability_verified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="disponibilidad verificada en",
            ),
        ),
        migrations.AddField(
            model_name="capturedproperty",
            name="availability_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="availability_verified_captured_properties",
                to=settings.AUTH_USER_MODEL,
                verbose_name="disponibilidad verificada por",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturedproperty",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("availability_verification_state", "unknown"),
                        ("availability_verified_at__isnull", True),
                        ("availability_verified_by__isnull", True),
                    )
                    | models.Q(
                        ("availability_verification_state__in", ["confirmed", "unavailable"]),
                        ("availability_verified_at__isnull", False),
                        ("availability_verified_by__isnull", False),
                    )
                ),
                name="capture_availability_verification_consistent",
            ),
        ),
    ]
