# Generated by Django 5.1.15 on 2026-04-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('provider_code', models.CharField(choices=[('openai', 'OpenAI'), ('qwen', 'Qwen'), ('deepseek', 'DeepSeek'), ('other', 'Otro')], default='openai', max_length=20, verbose_name='proveedor')),
                ('model_name', models.CharField(max_length=120, verbose_name='modelo')),
                ('base_url', models.URLField(blank=True, verbose_name='base URL')),
                ('api_key', models.TextField(blank=True, verbose_name='API key')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='proveedor por defecto')),
                ('supports_web_search', models.BooleanField(default=True, verbose_name='soporta búsqueda web')),
                ('supports_reasoning', models.BooleanField(default=True, verbose_name='soporta reasoning')),
                ('priority_order', models.PositiveSmallIntegerField(default=10, verbose_name='prioridad de fallback')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de proveedor IA',
                'verbose_name_plural': 'Configuraciones de proveedores IA',
                'ordering': ['priority_order', 'name'],
                'indexes': [models.Index(fields=['provider_code'], name='ia_aiprovid_provide_ad2a16_idx'), models.Index(fields=['is_active'], name='ia_aiprovid_is_acti_37b88f_idx'), models.Index(fields=['is_default'], name='ia_aiprovid_is_defa_7c1f8a_idx'), models.Index(fields=['priority_order'], name='ia_aiprovid_priorit_d59065_idx')],
            },
        ),
    ]
