# Generated by Django 5.1.15 on 2026-04-23 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='nombre de la empresa')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='email principal')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('company_website', models.URLField(blank=True, verbose_name='web')),
                ('company_notes', models.TextField(blank=True, verbose_name='información relevante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('default_ai_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_default', to='ia.aiproviderconfig', verbose_name='proveedor IA por defecto')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
