# Generated by Django 5.1.15 on 2026-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='logo'),
        ),
    ]
