# Generated by Django 5.1.15 on 2026-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='login_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='logo para login'),
        ),
    ]
