# Generated by Django 5.1.15 on 2026-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings_login_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Icono pequeño del navegador. Recomendado: PNG/ICO cuadrado.', null=True, upload_to='branding/', verbose_name='favicon'),
        ),
    ]
