# Generated by Django 5.1.15 on 2026-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='public_logo',
            field=models.ImageField(blank=True, help_text='Logo recomendado para la landing pública sobre fondo claro.', null=True, upload_to='branding/', verbose_name='logo público / landing'),
        ),
    ]
