# Generated by Django 5.1.15 on 2026-05-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_public_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='teléfono')),
                ('profile_type', models.CharField(choices=[('investor', 'Inversor particular'), ('captor', 'Captador inmobiliario'), ('agency', 'Inmobiliaria / agencia'), ('operator', 'Pequeño operador'), ('other', 'Otro')], default='investor', max_length=20, verbose_name='perfil')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Contactado'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='estado')),
                ('source_domain', models.CharField(blank=True, default='sooi.io', max_length=120, verbose_name='dominio origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'Solicitud de demo',
                'verbose_name_plural': 'Solicitudes de demo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='core_demore_email_95c29b_idx'), models.Index(fields=['status'], name='core_demore_status_26d5fc_idx'), models.Index(fields=['created_at'], name='core_demore_created_2c1b73_idx')],
            },
        ),
    ]
