# Generated by Django 5.1.15 on 2026-06-09 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_demorequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='inicio de trial')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='fin de trial')),
                ('is_trial', models.BooleanField(default=True, verbose_name='en periodo de trial')),
                ('signup_source', models.CharField(default='self_service', max_length=50, verbose_name='origen de registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
