# Generated by Django 5.1.15 on 2026-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('code', models.SlugField(unique=True, verbose_name='código')),
                ('base_url', models.URLField(blank=True, verbose_name='url base')),
                ('source_type', models.CharField(choices=[('portal', 'Portal'), ('web', 'Web'), ('manual', 'Manual'), ('api', 'API')], default='portal', max_length=20, verbose_name='tipo de fuente')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='fuentes_sou_code_6af74f_idx'), models.Index(fields=['is_active'], name='fuentes_sou_is_acti_2b9928_idx'), models.Index(fields=['source_type'], name='fuentes_sou_source__f6d46d_idx')],
            },
        ),
    ]
