# Generated by Django 5.1.15 on 2026-04-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='verificada'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_verified'], name='fuentes_sou_is_veri_8bb200_idx'),
        ),
    ]
